### ISSUE TITLE
what's wrong with my code~~~

### ISSUE THREAD

**Issue by SecretCastle** [theKashey/react-imported-component#2]
i'm sorry to disturb you, i have a question

here is my code 

```
import { AppContainer } from 'react-hot-loader'
import App from './app';


const render = (Component) => (
  ReactDOM.render(
    <AppContainer>
      <Component/>
    </AppContainer>,
    document.getElementById('app')
  )
)

render(App);

if(module.hot){
  module.hot.accept('./app', () => {
    render(App)
  });
}
```

```app
class App extends React.Component {
  render() {
    return (
      <div>
        <DashBorad />
      </div>
    )
  }
}
```

and  i  load asynchronous component , like this

```
const AsynComp = ImportComponent(() => import('./components/comp'))
const AsynCp1 = ImportComponent(() => import('./components/comp/cp1'))
const AsynCp2 = ImportComponent(() => import('./components/comp/cp2'))
class DashBoard extends React.Component {
  render() {
    return (
      <div>DashBoard <AsynComp /> <AsynCp1 /> <AsynCp2 /></div>
    )
  }
}
```

```
class Comp extends React.Component {
  render() {
    return (
      <div>reload</div>
    )
  }
}

export default Comp;
```

but when i run my code and modify that ,  show error:

```
bundle.js:46536 Uncaught ReferenceError: payload is not defined
    at Object.reset (http://localhost:8080/bundle.js:46536:22)
    at http://localhost:8080/bundle.js:46751:33
    at module.exports (http://localhost:8080/bundle.js:5380:25)
    at queue.(anonymous function) (http://localhost:8080/bundle.js:4124:7)
    at Number.run (http://localhost:8080/bundle.js:4110:5)
    at MessagePort.listener (http://localhost:8080/bundle.js:4114:7)
```

what config parameters i forget？？

ps: sorry about my english is bad

**Comment by theKashey** [comment]
No, the problem was in mine code. Dreadful, Dreadful sorry.
Nodejs tests did not cover HRL environment, I did only manual testing. A did it bad :(

Jump update to the latest version, and everything will be great!
